### ISSUE TITLE
Specify package version in `requirements.txt`

### ISSUE THREAD

**Issue by ruancomelli** [elvis-sik/muscle_synergies#1]
Very interesting repo, I'm curious to see how it will develop with time!

I'd like to suggest that you include specific package versions in `requirements.txt` and `requirements.dev.txt`. For instance, instead of just writing `pandas`, you should specify `pandas==1.2.1`. This can avoid a lot of headache in the future, and you can find more details by Googling this or reading the [StackOverflow question "Does Python requirements file have to specify version?"](https://stackoverflow.com/q/55052434/5811400).

I personally had this problem when using TensorFlow in a project. All was going well until TF2.0 came to life and suddenly `pip install -r requirements.txt` start to spit a lot of error messages. This is because, of course, as soon as TF2.0 became available, pip gave preference to installing it instead, and that broke compatibility with other packages which required TF1.x.

**Comment by elvis-sik** [comment]
Thank you for for the good tip and for checking it out! It's a good idea, I'll do it later.

**Comment by elvis-sik** [comment]
Hey Ruan, it's done. Thanks again for the suggestion and have a great week ;)
